"""LLM extraction model — fields generated by the LLM via outlines-cascade.

This file is configuration: edit it to change what the LLM extracts.
The LLM sees ONLY these fields. Link, date, and publisher are copied
verbatim from the raw feed AFTER generation to prevent hallucination.

The web UI auto-generates filter controls from the Literal types here.
"""

from typing import Literal

from pydantic import BaseModel, Field


class LLMExtraction(BaseModel):
    """Structured output generated by the LLM from press release content.

    Do NOT add url/date/publisher fields here — they are auto-populated
    from the raw feed in ProcessedRelease.
    """

    topic: Literal[
        "Consumer prices",
        "Producer prices",
        "Import prices",
        "Export prices",
        "GDP",
        "Industrial production",
        "Services production",
        "International trade",
        "Labour market",
        "Public finance",
        "Retail trade",
        "Construction",
        "Business surveys",
        "Other economic topics",
        "Non-economic topics",
    ] = Field(description="Primary topic of the press release")

    country: Literal[
        "Euro area",
        "Italy",
        "Spain",
        "France",
        "Germany",
        "Ireland",
        "Other",
    ] = Field(description="Geographic scope of the data")

    sentiment: Literal[
        "positive",
        "negative",
        "neutral",
    ] = Field(description="Economic sentiment conveyed by the data")

    summary_en: str = Field(
        description="Concise English summary of the press release (max 150 words)"
    )

    key_figures: str = Field(
        description=(
            "Key numerical figures mentioned: rates, percentages, index values, "
            "growth rates. Semi-colon-separated. (max 100 characters)"
        )
    )
